<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <parent>
        <groupId>com.smile.mall</groupId>
        <artifactId>smile-mall-security</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>smile-mall-security-common</artifactId>

    <modelVersion>4.0.0</modelVersion>

    <description>商城安全模块后台公共部分</description>

    <dependencies>

        <dependency>
            <groupId>com.smile.mall</groupId>
            <artifactId>smile-mall-service</artifactId>
            <version>${smile.mall.version}</version>
        </dependency>

        <!--验证码验证组件-->
        <dependency>
            <groupId>com.anji-plus</groupId>
            <artifactId>captcha</artifactId>
            <version>1.3.0</version>
        </dependency>

        <!-- OpenAPI 支持 -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        </dependency>
    </dependencies>


</project>