<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    
    <parent>
		<artifactId>smile-mall</artifactId>
		<groupId>com.smile.mall</groupId>
		<version>1.0-SNAPSHOT</version>
	</parent>
    
    <modelVersion>4.0.0</modelVersion>

    <artifactId>smile-mall-security</artifactId>

    <description>商城安全模块</description>
	<packaging>pom</packaging>

    <modules>
		<module>smile-mall-security-api</module>
		<module>smile-mall-security-admin</module>
		<module>smile-mall-security-common</module>
	</modules>


</project>